openapi: 3.0.0
info:
  version: v1.0.0
  title: ''
  description: ''
paths:
  /service-info:
    get:
      description: Returns information about the ingest service
      operationId: ingest_operations.get_service_info
      responses:
        200:
          description: Retrieve info about the ingest service
          content:
            application/json:
              schema:
                type: object
  /s3-credential:
    post:
      description: Add credentials for an S3 bucket
      operationId: ingest_operations.add_s3_credential
      requestBody:
        $ref: '#/components/requestBodies/S3CredentialRequest'
      parameters:
        - in: header
          name: Authorization
          schema:
            $ref: '#/components/schemas/BearerToken'
          required: true
      responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: object
  /genomic:
    post:
      description: Add linkages between clinical donors and genomic data.
      operationId: ingest_operations.add_genomic_linkages
      requestBody:
        $ref: '#/components/requestBodies/GenomicIngestRequest'
      responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: object
  /clinical:
    post:
      description: Add a list of donors with clinical data produced by the clinical ETL.
      operationId: ingest_operations.add_clinical_donors
      requestBody:
        $ref: "#/components/requestBodies/ClinicalDonorRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        422:
          description: User error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        401:
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        403:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
components:
  requestBodies:
    S3CredentialRequest:
      content:
        'application/json':
          schema:
            type: object
            properties:
              endpoint:
                type: string
                description: URL to the endpoint
                example: http://candig.docker.internal:9000
              bucket:
                type: string
                description: name of the bucket
              access_key:
                type: string
                description: access key for the bucket
              secret_key:
                type: string
                description: secret key for the bucket
            required:
              - endpoint
              - bucket
              - access_key
              - secret_key
    GenomicIngestRequest:
      content:
        'application/json':
          schema:
            type: array
            items:
              $ref: "#/components/schemas/GenomicSample"
    ClinicalDonorRequest:
      content:
        'application/json':
          schema:
            $ref: "#/components/schemas/ClinicalETLMap"
  schemas:
    ClinicalETLMap:
      type: object
      properties:
        openapi_url:
          type: string
          description: URL of schema used to generate this mapping
        donors:
          type: array
          items:
            type: object
            description: A DonorWithClinicalData object, as specified in the schema in openapi_url
        katsu_sha:
          type: string
          description: the SHA of the version of Katsu used to generate the schema.
        statistics:
          $ref: "#/components/schemas/Statistics"
    Statistics:
      type: object
      properties:
        required_but_missing:
          type: object
          description: for each schema, a count of required fields that are present vs missing
        schemas_used:
          type: array
          description: a list of schemas used in this dataset
          items:
            type: string
        cases_missing_data:
          type: array
          description: a list of cases that have missing data
          items:
            type: string
        schemas_not_used:
          type: array
          description: a list of schemas that are never used in this dataset
        summary_cases:
          type: object
          description: overall completeness counts
          properties:
            complete_cases:
              type: integer
              description: how many cases have complete data
            total_cases:
              type: integer
              description: how many cases are in this dataset
    GenomicSample:
      type: object
      properties:
        program_id:
          type: string
          description: Name of the cohort this sample belongs to. The user must be authorized to add data to this cohort.
        genomic_id:
          type: string
          description: A unique name for this genomic data resource
          example: "HG00096.vcf"
        metadata:
          type: object
          description: Additional data that describes the genomic resource
          properties:
            sequence_type:
              type: string
              description: type of data sequenced (whole genome or whole transcriptome)
              enum:
                - wgs
                - wts
              default: wgs
            data_type:
              type: string
              description: type of data represented in the resource (variant or read)
              enum:
                - variant
                - read
            reference:
              type: string
              description: which reference genome was used for alignment
              enum:
                - hg37
                - hg38
              default: hg38
        main:
          $ref: "#/components/schemas/File"
        index:
          $ref: "#/components/schemas/File"
        samples:
          type: array
          description: An array of links between donor data (e.g. MoH Sample Registrations) and the samples in the genomic data resource
          items:
            $ref: "#/components/schemas/SampleLink"
      required:
        - program_id
        - genomic_id
        - metadata
        - main
        - samples
    File:
      type: object
      description: Object describing a file
      properties:
        name:
          type: string
          description: name of the file, including all extensions
        access_method:
          type: string
          description: fully-described URI to the file
          anyOf:
            - $ref: "#/components/schemas/S3Access"
            - $ref: "#/components/schemas/FileAccess"
    FileAccess:
      type: string
      description: an absolute path to a local file on the HTSGet server itself, expressed as a file URI
      pattern: file:\/\/\/(.+)
      example: file:///data/samples/HG00096.vcf.gz
    S3Access:
      type: string
      description: a description of an S3 URI
      pattern: s3:\/\/(.+)\/(.+)\/(.+)
      example: s3://s3.us-east-1.amazonaws.com/1000genomes/HG00096.vcf.gz
    SampleLink:
      type: object
      description: Link between donor data (e.g. MoH Sample Registrations) and the samples in the genomic data resource
      properties:
        donor_sample_id:
          type: string
          description: the name of the sample as listed in the linked donor data
          example: sample_registration_id_1
        genomic_sample_id:
          type: string
          description: the name of the sample in the genomic data resource
          example: TUMOUR/NORMAL/PROGRAM_SAMPLE_REGISTRATION_ID_1
      required:
        - donor_sample_id
        - genomic_sample_id
    BearerToken:
      type: string
      description: An Authorization BearerToken header
      pattern: Bearer .+
    IngestResponse:
      type: object
      properties:
        result:
          type: string
          example: "Ingested 10 Donors"
        response_code:
          type: integer
          example: 0
        response_code_readable:
          type: string
          example: "Success"