openapi: 3.0.0
info:
  version: v1.0.0
  title: ''
  description: ''
paths:
  /service-info:
    get:
      description: Returns information about the ingest service
      operationId: ingest_operations.get_service_info
      responses:
        200:
          description: Retrieve info about the ingest service
          content:
            application/json:
              schema:
                type: object
  /s3-credential:
    post:
      description: Add credentials for an S3 bucket
      operationId: ingest_operations.add_s3_credential
      requestBody:
        $ref: '#/components/requestBodies/S3CredentialRequest'
      parameters:
        - in: header
          name: Authorization
          schema:
            $ref: '#/components/schemas/BearerToken'
          required: true
      responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: object
  /genomic:
    post:
      description: Add linkages between clinical donors and genomic data.
      operationId: ingest_operations.add_moh_variant
      requestBody:
        $ref: '#/components/requestBodies/GenomicIngestRequest'
      responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: object
  /clinical:
    post:
      description: Add a list of donors with clinical data produced by the clinical ETL.
      operationId: ingest_operations.add_clinical_donors
      requestBody:
        $ref: "#/components/requestBodies/ClinicalDonorRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        422:
          description: User error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        401:
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        403:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngestResponse"
components:
  parameters:
    ProgramId:
      in: path
      name: program_id
      required: true
      description: name of an MoH program to ingest this genomic file into
      schema:
        type: string
  requestBodies:
    S3CredentialRequest:
      content:
        'application/json':
          schema:
            type: object
            properties:
              endpoint:
                type: string
                description: URL to the endpoint
                example: http://candig.docker.internal:9000
              bucket:
                type: string
                description: name of the bucket
              access_key:
                type: string
                description: access key for the bucket
              secret_key:
                type: string
                description: secret key for the bucket
            required:
              - endpoint
              - bucket
              - access_key
              - secret_key
    GenomicIngestRequest:
      content:
        'application/json':
          schema:
            type: object
            properties:
              genomic_id:
                type: string
                description: The name of the VCF file, including gz, if present
                example: "HG00096.vcf.gz"
              index:
                type: string
                description: The extension of the index file without the dot (tbi, crai...)
                example: "tbi"
              access_method:
                type: string
                anyOf:
                  - $ref: "#/components/schemas/S3Access"
                  - $ref: "#/components/schemas/FileAccess"
              samples:
                type: array
                items:
                  $ref: "#/components/schemas/VCFSample"
            required:
              - genomic_id
              - access_method
              - samples
              - index
    ClinicalDonorRequest:
      content:
        'application/json':
          schema:
            $ref: "#/components/schemas/ClinicalETLMap"
  schemas:
    S3Access:
      type: string
      description: a specification for an S3 bucket
      pattern: s3:\/\/(.+)\/(.+)
      example: s3://http://candig.docker.internal:9000/mohccn-data
    ClinicalETLMap:
      type: object
      properties:
        openapi_url:
          type: string
          description: URL of schema used to generate this mapping
        donors:
          type: array
          items:
            type: object
            description: A DonorWithClinicalData object, as specified in the schema in openapi_url
        katsu_sha:
          type: string
          description: the SHA of the version of Katsu used to generate the schema.
        statistics:
          $ref: "#/components/schemas/Statistics"
    Statistics:
      type: object
      properties:
        required_but_missing:
          type: object
          description: for each schema, a count of required fields that are present vs missing
        schemas_used:
          type: array
          description: a list of schemas used in this dataset
          items:
            type: string
        cases_missing_data:
          type: array
          description: a list of cases that have missing data
          items:
            type: string
        schemas_not_used:
          type: array
          description: a list of schemas that are never used in this dataset
        summary_cases:
          type: object
          description: overall completeness counts
          properties:
            complete_cases:
              type: integer
              description: how many cases have complete data
            total_cases:
              type: integer
              description: how many cases are in this dataset
    FileAccess:
      type: string
      description: a file path to a directory on the HTSGet server itself
      pattern: file:\/\/\/(.+)
      example: file://data/samples/
    VCFSample:
      type: object
      properties:
        sample_registration_id:
          type: string
          description: a SampleRegistrationId in the MoH program
          example: sample_registration_id_1
        sample_name_in_file:
          type: string
          description: the name of the sample in the VCF file
          example: TUMOUR/NORMAL/PROGRAM_SAMPLE_REGISTRATION_ID_1/...
      required:
        - sample_registration_id
        - sample_name_in_file
    BearerToken:
      type: string
      description: An Authorization BearerToken header
      pattern: Bearer .+
    IngestResponse:
      type: object
      properties:
        result:
          type: string
          example: "Ingested 10 Donors"
        response_code:
          type: integer
          example: 0
        response_code_readable:
          type: string
          example: "Success"