name: Dispatch
on:
    push:
        branches: [develop]
jobs:
  CanDIG-dispatch:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'mshadbolt/CanDIGv2'
      CHECKOUT_BRANCH: 'develop'
      PR_AGAINST_BRANCH: 'develop'
      OWNER: 'mshadbolt'
    steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - uses: actions/github-script@v6
              id: get_pr_data
              with:
                script: |
                    return (
                      await github.rest.repos.listPullRequestsAssociatedWithCommit({
                        commit_sha: context.sha,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                      })
                    ).data[0];
            - name: Pull Request data
              run: |
                echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
                echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'
            - name: Create PR in CanDIGv2
              id: make_pr
              uses: jman005/github-action-pr-expanded@v0
              with:
                  github_token: ${{ secrets.SUBMODULE_PR }}
                  parent_repository: ${{ env.PARENT_REPOSITORY }}
                  checkout_branch: ${{ env.CHECKOUT_BRANCH}}
                  pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
                  pr_title: 'Submodule update from merging: ${{ fromJson(steps.get_pr_data.outputs.result).title }}'
                  pr_description: "PR triggered by update to develop branch on ${{ github.repository }}. Commit hash: `${{ github.sha }}`."
                  owner: ${{ env.OWNER }}
                  submodule_path: lib/candig-ingest/candigv2-ingest
                  label: Submodule update
