name: Submodule PR
on:
    push:
        branches: [develop]
jobs:
  CanDIG-dispatch:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'CanDIG/CanDIGv2'
      CHECKOUT_BRANCH: 'develop'
      PR_AGAINST_BRANCH: 'develop'
      OWNER: 'CanDIG'
    steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Create PR in CanDIGv2
              id: make_pr
              uses: CanDIG/github-action-pr-expanded@v2
              with:
                  github_token: ${{ secrets.SUBMODULE_PR }}
                  parent_repository: ${{ env.PARENT_REPOSITORY }}
                  checkout_branch: ${{ env.CHECKOUT_BRANCH}}
                  pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
                  owner: ${{ env.OWNER }}
                  submodule_path: lib/candig-ingest/candigv2-ingest
                  label: Submodule update
