name: Dispatch
on:
    push:
        branches: [develop]
jobs:
  CanDIG-dispatch:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'CanDIG/CanDIGv2'
      CHECKOUT_BRANCH: 'develop'
      PR_AGAINST_BRANCH: 'develop'
      OWNER: 'CanDIG'
    steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Get Submodule PR name
              id: get_pr_name
              run: |
                PR_NAME=$(curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.title')
                echo "::set-output name=PR_NAME::$PR_NAME"
            - name: Create PR in CanDIGv2
              id: make_pr
              uses: jman005/github-action-pr-expanded@v0
              with:
                  github_token: ${{ secrets.SUBMODULE_PR }}
                  parent_repository: ${{ env.PARENT_REPOSITORY }}
                  checkout_branch: ${{ env.CHECKOUT_BRANCH}}
                  pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
                  pr_description: "PR triggered by update to develop branch on ${{ github.repository }}. Commit hash: `${{ github.sha }}`."
                  owner: ${{ env.OWNER }}
                  submodule_path: lib/candig-ingest/candigv2-ingest
                  label: Submodule update
