name: Github Actions Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      CANDIG_URL: "http://localhost"
      HTSGET_URL: "http://localhost/genomics"
      VAULT_URL: "http://localhost/vault"
      IS_TESTING: true
      SERVICE_NAME: "candig-ingest"
      APPROLE_TOKEN_FILE: ${{github.workspace}}/approle-token
      ROLE_ID_FILE: ${{github.workspace}}/roleid
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Add files
        run: |
          echo "sdfsdfs" > ${{ env.APPROLE_TOKEN_FILE }}
          echo "sdfsdfs" > ${{ env.ROLE_ID_FILE }}
      - name: Test with pytest
        run: |
          pytest
